Algoritmo "semnome"
//Desenvolver um programa que pergunte ao usuario o seu nome completo
//e seu sexo.Em seguida, o programa deve apresentar
//os dados anteriormente informados
Var

Nome, sexo:caractere

Inicio

Escreval ("Informe o seu nome completo:")
Leia (Nome)
Escreval ("Informe o seu sexo")
Leia (sexo)
EScreval ("Olá ", Nome, " Seja bem vindo(a)!")
Escreval ("O seu sexo informado é " , Sexo)
escreva ("É muito bom ter ver aqui!")

Fimalgoritmo