Algoritmo "semnome"
//Elaborar um programa que pergunte quatro valores inteiros e
// apresente 2 resultados

Var
N1, N2, N3, N4, S, M:Inteiro


Inicio
escreval("Digite 1º número:")
Leia (N1)
Escreval ("Digite o 2º número ")
Leia (N2)
Escreval ("Digite o 3º número")
Leia (N3)
Escreval ("Digite o 4º número")
Leia (N4)
S <- N1+N2+N3+N4
Escreval ("A soma dos 4 números informados é: " , S)

M <- N1*N2*N3*N4
Escreval ("A multiplicação dos 4 números informados anteriormente é:"  , M)

Fimalgoritmo