Algoritmo "3 perguntas "
// Fazer um algoritmo que pergunte  1 numero e apresente:
// a)o proprio numero
//b)o quadrado deste numero
//c)a raiz quadrada deste numero
Var
numero, quadrado, raiz:real


Inicio
Escreva(" Digite um número:")
leia(numero)
quadrado <- numero ^ 2
raiz <- RaizQ(numero)
Escreval("O número digitado é:", numero)
Escreval("O quadrado deste número é:", quadrado)
Escreval("A raiz quadrada deste número é:", raiz)


Fimalgoritmo